name: branch

on:
  push:
    branches-ignore: [main, gh-pages]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: wtnb75/actions/python@main
      with:
        pipinstall: ".[dev]"
    - uses: wtnb75/actions/flake8@main
      with:
        dirs: "enumset tests"
    - uses: wtnb75/actions/pytest@heredoc
      with:
        test-readme: .
    - uses: wtnb75/actions/wheel@main
    - uses: wtnb75/actions/pdoc@main
      with:
        output-dir: doc
        module: enumset
    - uses: wtnb75/actions/merge-pages@main
      with:
        dirs: cover doc
        pydist: dist
